import { GoogleGenerativeAI } from "@google/generative-ai";
import { PERSONAS, PersonaId } from "./personas";
import { getActiveModel } from "./voice-training-service";
import { verifyConstraints } from "./constraint-service";

/**
 * GENERATED ASSETS SCHEMA
 * -----------------------
 * Represents the structured specific output generated by the AI.
 */
export interface GeneratedAssets {
  /** The main LinkedIn text post content (filtered & formatted). */
  textPost: string;
  /** Detailed prompt for image generation (Visualize Value style). */
  imagePrompt: string;
  /** 60-second video script for vertical video content. */
  videoScript: string;
  /** Optional URL of the generated image (if image generation was successful). */
  imageUrl?: string;
}

// OpenAI generation for custom voice
async function generateWithOpenAI(
  input: string, 
  apiKey: string, 
  modelId: string
): Promise<GeneratedAssets> {
  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: modelId,
      messages: [
        {
          role: 'system',
          content: 'You are a LinkedIn content creator. Write in this exact style and voice. Generate a LinkedIn post, an image prompt, and a video script in JSON format.'
        },
        {
          role: 'user',
          content: `Create content about: ${input}

Return JSON with these keys:
- textPost: The LinkedIn post
- imagePrompt: A "Visualize Value" style image prompt (minimalist, white on black)
- videoScript: A 60-second video script`
        }
      ],
      temperature: 0.7,
      response_format: { type: "json_object" },
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(`OpenAI generation failed: ${error.error?.message || 'Unknown error'}`);
  }

  const data = await response.json();
  const content = data.choices[0].message.content;
  
  try {
    const parsed = JSON.parse(content);
    return {
      textPost: parsed.textPost || parsed.text_post || parsed.post || "",
      imagePrompt: parsed.imagePrompt || parsed.image_prompt || "Minimalist vector line art. White on black. High contrast.",
      videoScript: parsed.videoScript || parsed.video_script || parsed.script || "",
    };
  } catch {
    // Fallback if JSON parsing fails
    return {
      textPost: content,
      imagePrompt: "Minimalist vector line art. White on black. High contrast.",
      videoScript: `Script based on: ${content.substring(0, 100)}...`,
    };
  }
}

/**
 * CORE GENERATION FUNCTION
 * ------------------------
 * Orchestrates the text generation process using Google Gemini.
 * 
 * Flow:
 * 1. Selects the System Prompt based on `personaId`.
 * 2. Configures the Gemini Model (currently using `gemini-3-flash-preview`).
 * 3. Constructs the User Prompt with specific instructions.
 * 4. Calls the LLM and parses the JSON response.
 * 5. Validates the output against constraints (Length, Formatting).
 * 6. Retries automatically if validation fails.
 * 
 * @param input The raw user input (Topic or URL).
 * @param apiKey Google Gemini API Key.
 * @param personaId The selected persona (default: 'cso').
 */
export async function generateContent(
  input: string,
  apiKey: string,
  personaId: PersonaId = "cso",
  openaiKey?: string
): Promise<GeneratedAssets> {
  // MOCK MODE for Testing/Demo if key is 'demo'
  if (apiKey.toLowerCase().trim() === "demo") {
    await new Promise(r => setTimeout(r, 2000));
    const personaName = PERSONAS[personaId]?.name || "Unknown";
    return {
      textPost: `[MOCK ${personaName.toUpperCase()} OUTPUT]\n\nSuccess is about avoiding stupidity.\n\nMost people think they need to be smart.\n\nThey are wrong.\n\nYou just need to not be stupid.\n\n- Avoid ruin.\n- Survive long enough.\n- Let compounding work.\n\n(Generated by ${personaName})`,
      imagePrompt: "Minimalist vector line art. White on black. High contrast. A maze with one clear exit path.",
      videoScript: "HOOK: Stop trying to be smart. It's killing your gains.\n\nCUT TO: Black screen, white text 'AVOID STUPIDITY'.\n\nVO: In a world of geniuses, the survivor wins."
    };
  }

  // Check if using custom voice with fine-tuned model
  if (personaId === "custom" && openaiKey && openaiKey !== "demo") {
    try {
      const activeModel = await getActiveModel();
      
      if (activeModel && activeModel.openaiModelId) {
        console.log(`Using custom voice model: ${activeModel.openaiModelId}`);
        return await generateWithOpenAI(input, openaiKey, activeModel.openaiModelId);
      } else {
        console.warn("Custom persona selected but no trained model found, falling back to Gemini");
      }
    } catch (e) {
      console.warn("Failed to load custom voice model, falling back to Gemini:", e);
    }
  }

  // Default: Use Gemini
  const genAI = new GoogleGenerativeAI(apiKey);
  
  // Select the correct system prompt
  const selectedPersona = PERSONAS[personaId] || PERSONAS.cso;
  // Use gemini-3-flash-preview as it successfully bypasses current rate limits
  const model = genAI.getGenerativeModel({ 
    model: "gemini-3-flash-preview", 
    systemInstruction: selectedPersona.systemPrompt 
  });

  const prompt = `
    Analyze this input and generate 3 assets:
    1. LinkedIn Text Post (following the rules).
    2. "Visualize Value" Image Prompt (Minimalist vector line art, white on black, geometric representation of the concept).
    3. 60s Video Script (Cinematic, viral hook, regular retention cuts).

    INPUT:
    "${input}"

    Ensure the response is valid JSON.
  `;

    // RETRY LOOP: Enforce Constraints
    let attempts = 0;
    const MAX_ATTEMPTS = 2; // Original + 2 Retries

    let currentPrompt = prompt;

    while (attempts <= MAX_ATTEMPTS) {
        attempts++;
        try {
            console.log(`[AI Service] Generation Attempt ${attempts}...`);
            const result = await model.generateContent({
                contents: [{ role: "user", parts: [{ text: currentPrompt }] }],
                generationConfig: { responseMimeType: "application/json" }
            });

            const content = result.response.text();
            if (!content) throw new Error("No content generated");
            
            const parsed = JSON.parse(content);
            const textPost = parsed.textPost || parsed.text_post || "";

            // VERIFY CONSTRAINTS
            const validation = verifyConstraints(textPost);

            if (validation.valid) {
                console.log("[AI Service] Constraint Check Passed ✅");
                return {
                    textPost,
                    imagePrompt: parsed.imagePrompt || parsed.image_prompt || "",
                    videoScript: parsed.videoScript || parsed.video_script || "",
                };
            }

            console.warn(`[AI Service] Constraint Failed ❌: ${validation.reason}`);
            
            // If failed, assume we need to retry unless we run out of attempts
            if (attempts <= MAX_ATTEMPTS) {
                currentPrompt += `\n\nCRITICAL SYSTEM ALERT: The previous output failed verification. \nREASON: ${validation.reason}\n\nFIX: Rewrite the hook to be shorter. Strict limit: 210 chars.`;
            } else {
                 console.warn("[AI Service] Max attempts reached. Returning best effort.");
                 return {
                    textPost: `[CONSTRAINT FAILED] ${textPost}`, // Mark it visibly for debugging, or just return it.
                    imagePrompt: parsed.imagePrompt || parsed.image_prompt || "",
                    videoScript: parsed.videoScript || parsed.video_script || "",
                };
            }

        } catch (e: unknown) {
             const errorMessage = e instanceof Error ? e.message : "Unknown error";
             console.error(`[AI Service] Attempt ${attempts} Error`, e);
             
             // GRACEFUL FALLBACK FOR 429 / QUOTA / NETWORK ERRORS
             // This ensures the app "runs perfectly" even if Google API is unstable or rate-limited.
             if (errorMessage.includes("429") || errorMessage.includes("503") || errorMessage.includes("500") || errorMessage.includes("fetch failed")) {
                console.warn("[AI Service] Hit API Limit or Network Error. Switching to Backup Content.");
                return {
                    textPost: `[BACKUP MODE: API BUSY]\n\nConsistency beats intensity.\n\nEveryone starts strong.\nFew finish.\n\nThe secret isn't a hack.\nIt's showing up when you don't want to.\n\nDon't break the chain.`,
                    imagePrompt: "Minimalist vector lines showing a consistent upward trend vs erratic spikes. White on black.",
                    videoScript: "HOOK: Why do 99% of people fail?\n\nCUT TO: Graph showing jagged spikes then a crash.\n\nVO: They rely on motivation.\n\nCUT TO: Straight rising line.\n\nVO: Winners rely on discipline.",
                };
             }

             if (attempts > MAX_ATTEMPTS) throw e;
        }
    }

    throw new Error("AI Generation failed after max retries.");
  }
