
"use server";

import { getServerSession } from "next-auth";
import { authOptions } from "../utils/auth";
import { prisma } from "../utils/db";
import { publishToLinkedIn } from "../utils/platforms/linkedin-api";
import { publishToTwitter } from "../utils/platforms/twitter-api";

export async function publishPostAction(strategyId: string, platform: "linkedin" | "twitter" = "linkedin") {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
        throw new Error("Unauthorized");
    }

    // 1. Fetch Strategy
    const strategy = await prisma.strategy.findUnique({
        where: { id: strategyId }
    });

    if (!strategy) throw new Error("Strategy not found");
    if (strategy.authorId !== session.user.id) throw new Error("Unauthorized access to strategy");

    // 2. Publish
    if (platform === "linkedin") {
        try {
            const result = await publishToLinkedIn(session.user.id, strategy.content);
            
            // 3. Update Database
            await prisma.strategy.update({
                where: { id: strategyId },
                data: {
                    isPublished: true,
                    publishedAt: new Date(),
                    externalId: result.externalId
                }
            });

            return { success: true, url: result.url };
        } catch (e: any) {
            console.error("Publish Action Failed", e);
            return { success: false, error: e.message };
        }
    }

    if (platform === "twitter") {
        try {
            // Check if strategy has specific X thread content, otherwise fallback to split text
            // For now, we pass the raw content and let api split it, OR we could pass xThread array
            // Let's assume we pass raw content for now to keep action signature simple
            // Improvement: Strategy model should have xThread field accessible here?
            // Actually, strategy.content is the main text. 
            // If we want to publish the "Thread" generated by Transmute, we need to access that.
            // But Strategy model schema might not have specific columns for xThread yet.
            // We usually store xThread in JSON or separate field. 
            // For MVP: We publish the "content" via splitIntoTweets.
            
            const result = await publishToTwitter(session.user.id, strategy.content);
            
             // 3. Update Database
             await prisma.strategy.update({
                where: { id: strategyId },
                data: {
                    isPublished: true,
                    publishedAt: new Date(),
                    externalId: result.externalId
                }
            });

            return { success: true, url: result.url };
        } catch (e: any) {
            console.error("Twitter Publish Action Failed", e);
            return { success: false, error: e.message };
        }
    }

    return { success: false, error: "Platform not supported yet" };
}
